name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to Server
        env:
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          sshpass -p "$SERVER_PASSWORD" \
ssh -o StrictHostKeyChecking=no \
"$SERVER_USERNAME@$SERVER_IP" << 'EOF'
  set -e

  cd borsbaba

  # Start ssh-agent only if not already running
  if [ -z "$SSH_AUTH_SOCK" ]; then
    eval "$(ssh-agent -s)"
  fi

  ssh-add ~/gith

  git stash
  git pull

  yarn install
  yarn build

  pm2 stop borsbaba || true
  pm2 delete borsbaba || true
  pm2 start "yarn start -p 3600" --name "borsbaba"
EOF

